# 
# ## Welcome in the Beloved Blocks configuration file ##
# 
# 


# Available languages: en_US, fr_FR.
# If empty, system language.
lang: 

tool:
    name: "Stonecutter"
    craftable: true
    itemGlow: true

blocks:
    slabs:
        stone:
            name: "Smooth Stone Double Slab"
            craftable: true
            itemGlow: true
        
        sandstone:
            name: "Smooth Sandstone Double Slab"
            craftable: true
            itemGlow: true
        
        red_sandstone:
            name: "Smooth Red Sandstone Double Slab"
            craftable: true
            itemGlow: true
