### BelovedBlocks configuration file ###

# Available languages: en-US, fr-FR, de-DE.
# If empty, system language.
lang:


# By default, internal items data are used to store the fact a block or tool is indeed a BelovedBlock
# item and not an old Minecraft one. The name of the item is not used for that.
# You can enable this option to use also the name as fallback. It could be useful if you are migrating
# from an older version of BelovedBlocks since the internal data are only used from BelovedBlocks 1.2.
# Enabling this option will prevent Beloved Blocks tools and blocks from being renamed.
useItemNamesFallback: false


# The "itemGlow" keys below enables or disables the enchantment effect on the item.


# Configuration for the tools (stonecutter and saw).
tool:
    stonecutter:
        name: "Stonecutter"
        craftable: true       # Crafted like the shears, with diamonds.
        itemGlow: true
        usageInLore: true     # Display infos on how to use in the tooltip of the tool. Warning, they will stay on already crafted items.

    wrench:
        name: "Wrench"
        craftable: true       
        itemGlow: true
        usageInLore: true

# Configuration for the blocks
blocks:
        
    portals:
        nether:
            name: "Nether Portal"
            craftable: true
            amountPerCraft: 16
            itemGlow: true

            # If set to true, illegal portal placements will be allowed (typically, two
            # portals next to each other).
            allowPortalsAnywhere: true
        end:
            name: "End Portal"
            craftable: true
            amountPerCraft: 16
            itemGlow: true

            # If set to true, illegal portal placements will be allowed (typically, two
            # portals next to each other).
            allowPortalsAnywhere: true
        gateway:
            name: "End Gateway"
            craftable: true
            amountPerCraft: 1
            itemGlow: true

            # If set to true, illegal portal placements will be allowed (typically, two
            # portals next to each other).
            allowPortalsAnywhere: true

    others:
        burning_furnace:
            name: "Indefinitely Burning Furnace"
            craftable: true   # Crafted with a furnace and a blaze powder (shapeless recipe)
            itemGlow: true
            
        burning_smoker:
            name: "Indefinitely Burning Smoker"
            craftable: true   # Crafted with a smoker and a blaze powder (shapeless recipe)
            itemGlow: true
            
        burning_bast_furnace:
            name: "Indefinitely Burning Blast Furnace"
            craftable: true   # Crafted with a blast furnace and a blaze powder (shapeless recipe)
            itemGlow: true

# Enables or disables the block changes of our tool being saved with LogBlock or Prism (if installed)
logs:
    logBlock: true
    prism: true
