# 
# ## Welcome in the Beloved Blocks configuration file ##
# 
# 


# Available languages: en_US, fr_FR.
lang: en_US

tool:
    name: "Magic tool"
    craftable: true

blocks:
    slabs:
        stone:
            name: "Smooth Stone Slab"
            craftable: true
        sandstone:
            name: "Smooth Sandstone Slab"
            craftable: true
        red_sandstone:
            name: "Smooth Red Sandstone Slab"
            craftable: true
