### BelovedBlocks configuration file ###

# Available languages: en-US, fr-FR, de-DE.
# If empty, system language.
lang:


# By default, internal items data are used to store the fact a block or tool is indeed a BelovedBlock
# item and not an old Minecraft one. The name of the item is not used for that.
# You can enable this option to use also the name as fallback. It could be useful if you are migrating
# from an older version of BelovedBlocks since the internal data are only used from BelovedBlocks 1.2.
# Enabling this option will prevent Beloved Blocks tools and blocks from being renamed.
useItemNamesFallback: false


# The "itemGlow" keys below enables or disables the enchantment effect on the item.


# Configuration for the tools (stonecutter and saw).
tool:
    stonecutter:
        name: "Stonecutter"
        craftable: true       # Crafted like the shears, with diamonds.
        itemGlow: true
        usageInLore: true     # Display infos on how to use in the tooltip of the tool. Warning, they will stay on already crafted items.

    saw:
        name: "Saw"
        craftable: true
        itemGlow: true
        usageInLore: true     # Display infos on how to use in the tooltip of the tool. Warning, they will stay on already crafted items.
        percentageToBreak: 1  # Configures the probability the item will break to prevent players abusing it. Setting it to 0 will disable the effect.
                              # Note that the item will be likely to break following this probability only if it is used  like a vanilla saw.
                              # Number between 0 and 100.


# Configuration for the blocks
blocks:
    slabs:
        stone:
            name: "Smooth Stone Double Slab"
            craftable: true   # Crafted with four slabs in a square.
            itemGlow: true
        
        sandstone:
            name: "Smooth Sandstone Double Slab"
            craftable: true   # Crafted with four slabs in a square.
            itemGlow: true
        
        red_sandstone:
            name: "Smooth Red Sandstone Double Slab"
            craftable: true   # Crafted with four slabs in a square.
            itemGlow: true
        
        quartz:
            name: "Smooth Quartz Double Slab"
            craftable: true   # Crafted with four slabs in a square.
            itemGlow: true
    
    logs:
        oak:
            name: "Smooth Oak Wood"
            craftable: true   # Crafted with four logs in a square.
            itemGlow: true
        
        spruce:
            name: "Smooth Spruce Wood"
            craftable: true   # Crafted with four logs in a square.
            itemGlow: true
        
        birch:
            name: "Smooth Birch Wood"
            craftable: true   # Crafted with four logs in a square.
            itemGlow: true

        jungle:
            name: "Smooth Jungle Wood"
            craftable: true   # Crafted with four logs in a square.
            itemGlow: true
        
        acacia:
            name: "Smooth Acacia Wood"
            craftable: true   # Crafted with four logs in a square.
            itemGlow: true
        
        dark_oak:
            name: "Smooth Dark Oak Wood"
            craftable: true   # Crafted with four logs in a square.
            itemGlow: true

    portals:
        nether:
            name: "Nether Portal"
            craftable: true
            amountPerCraft: 16
            itemGlow: true

            # If set to true, illegal portal placements will be allowed (typically, two
            # portals next to each other).
            allowPortalsAnywhere: true
        end:
            name: "End Portal"
            craftable: true
            amountPerCraft: 16
            itemGlow: true

            # If set to true, illegal portal placements will be allowed (typically, two
            # portals next to each other).
            allowPortalsAnywhere: true

    others:
        burning_furnace:
            name: "Indefinitely Burning Furnace"
            craftable: true   # Crafted with a furnace and a blaze powder (shapeless recipe)
            itemGlow: true


# Enables or disables the block changes of our tool being saved with LogBlock or Prism (if installed)
logs:
    logBlock: true
    prism: true
