api-version: 1.13
name: BelovedBlocks
description: All the secrets blocks, not only in your dreams!
main: eu.carrade.amaury.BelovedBlocks.BelovedBlocks
version: 1.2.2
authors: ["Amaury Carrade", "Florian Cassayre", "Adrien Prokopowicz"]

awareness:
  - !@UTF8

softdepend:
  - LogBlock
  - Prism

commands:
    belovedblocks:
        description: Get the blocks and tools added by BelovedBlocks
        aliases: [bb]
        usage: "See /<command>."

permissions:
    belovedblocks.*:
        default: op
        children:
            belovedblocks.give: true
            belovedblocks.use: true
            belovedblocks.craft: true
 
    belovedblocks.give.*:
        default: op
        children:
            belovedblocks.give.blocks: true
            belovedblocks.give.tools: true
 
    belovedblocks.give.blocks.*:
        default: op
        children:
            belovedblocks.give.blocks.end-portal: true
            belovedblocks.give.blocks.portal-nether: true
            belovedblocks.give.blocks.end-gateway: true
            belovedblocks.give.blocks.burning_furnace: true
            belovedblocks.give.blocks.burning_smoker: true
            belovedblocks.give.blocks.burning_bast_furnace: true
  
    belovedblocks.give.blocks.end-portal.*:
        default: op
        children:
            belovedblocks.give.blocks.end-portal.self: true
            belovedblocks.give.blocks.end-portal.other: true
  
    belovedblocks.give.blocks.portal-nether.*:
        default: op
        children:
            belovedblocks.give.blocks.portal-nether.self: true
            belovedblocks.give.blocks.portal-nether.other: true
            
    belovedblocks.give.blocks.end-gateway.*:
        default: op
        children:
            belovedblocks.give.blocks.end-gateway.self: true
            belovedblocks.give.blocks.end-gateway.other: true
 

    belovedblocks.give.tools.*:
        default: op
        children:
            belovedblocks.give.tools.wrench: true
            belovedblocks.give.tools.stonecutter: true
 
    belovedblocks.give.tools.wrench.*:
        default: op
        children:
            belovedblocks.give.tools.wrench.self: true
            belovedblocks.give.tools.wrench.other: true
 
    belovedblocks.give.tools.stonecutter.*:
        default: op
        children:
            belovedblocks.give.tools.stonecutter.self: true
            belovedblocks.give.tools.stonecutter.other: true
 
    belovedblocks.use.*:
        default: true
        children:
            belovedblocks.use.blocks: true
            belovedblocks.use.tools: true
 
    belovedblocks.use.blocks.*:
        default: true
        children:
            belovedblocks.use.blocks.end-portal: true
            belovedblocks.use.blocks.portal-nether: true
            belovedblocks.use.blocks.end-gateway: true
            belovedblocks.use.blocks.burning_furnace: true
            belovedblocks.use.blocks.burning_smoker: true
            belovedblocks.use.blocks.burning_bast_furnace: true

 
    belovedblocks.use.tools.*:
        default: true
        children:
            belovedblocks.use.tools.wrench: true
            belovedblocks.use.tools.stonecutter: true
 
    belovedblocks.craft.*:
        default: true
        children:
            belovedblocks.craft.blocks: true
            belovedblocks.craft.tools: true
 
    belovedblocks.craft.blocks.*:
        default: true
        children:
            belovedblocks.craft.blocks.end-portal: true
            belovedblocks.craft.blocks.portal-nether: true 
            belovedblocks.craft.blocks.end-gateway: true
            belovedblocks.craft.blocks.burning_furnace: true
            belovedblocks.craft.blocks.burning_smoker: true
            belovedblocks.craft.blocks.burning_bast_furnace: true
 
    belovedblocks.craft.tools.*:
        default: true
        children:
            belovedblocks.craft.tools.wrench: true
            belovedblocks.craft.tools.stonecutter: true
 
 

    belovedblocks.give.blocks.end-portal.self:
        description: "Allows the player to give the end portal of BelovedBlocks to itself."
        default: op
 
    belovedblocks.give.blocks.end-portal.other:
        description: "Allows the player to give the end portal of BelovedBlocks to others."
        default: op

    belovedblocks.give.blocks.portal-nether.self:
        description: "Allows the player to give the nether portal of BelovedBlocks to itself."
        default: op
 
    belovedblocks.give.blocks.portal-nether.other:
        description: "Allows the player to give the nether portal of BelovedBlocks to others."
        default: op
 
    belovedblocks.give.blocks.end-gateway.self:
        description: "Allows the player to give the end gateway of BelovedBlocks to itself."
        default: op
 
    belovedblocks.give.blocks.portal-nether.other:
        description: "Allows the player to give the end gateway of BelovedBlocks to others."
        default: op
                
    belovedblocks.give.blocks.burning_furnace.self:
        description: "Allows the player to give the burning_furnace of BelovedBlocks to itself."
        default: op
 
    belovedblocks.give.blocks.burning_furnace.other:
        description: "Allows the player to give the burning_furnace of BelovedBlocks to others."
        default: op
 
    belovedblocks.give.blocks.burning_smoker.self:
        description: "Allows the player to give the burning_smoker of BelovedBlocks to itself."
        default: op
 
    belovedblocks.give.blocks.burning_smoker.other:
        description: "Allows the player to give the burning_smoker of BelovedBlocks to others."
        default: op
 
    belovedblocks.give.blocks.burning_bast_furnace.self:
        description: "Allows the player to give the burning_bast_furnace of BelovedBlocks to itself."
        default: op
 
    belovedblocks.give.blocks.burning_bast_furnace.other:
        description: "Allows the player to give the burning_bast_furnace of BelovedBlocks to others."
        default: op
   
    belovedblocks.give.tools.wrench.self:
        description: "Allows the player to give the wrench of BelovedBlocks to itself."
        default: op
 
    belovedblocks.give.tools.wrench.other:
        description: "Allows the player to give the wrench of BelovedBlocks to others."
        default: op
 
    belovedblocks.give.tools.stonecutter.self:
        description: "Allows the player to give the stonecutter of BelovedBlocks to itself."
        default: op
 
    belovedblocks.give.tools.stonecutter.other:
        description: "Allows the player to give the stonecutter of BelovedBlocks to others."
        default: op
 
    belovedblocks.use.blocks.end-portal:
        description: "Allows the player to use the end portal of BelovedBlocks."
        default: true

    belovedblocks.use.blocks.portal-nether:
        description: "Allows the player to use the nether portal of BelovedBlocks."
        default: true
 
    belovedblocks.use.blocks.end-gateway:
        description: "Allows the player to use the end gateway of BelovedBlocks."
        default: true
                
    belovedblocks.use.blocks.burning_furnace:
        description: "Allows the player to use the burning_furnace of BelovedBlocks."
        default: true
 
    belovedblocks.use.blocks.burning_smoker:
        description: "Allows the player to use the burning_smoker of BelovedBlocks."
        default: true
 
    belovedblocks.use.blocks.burning_bast_furnace:
        description: "Allows the player to use the burning_bast_furnace of BelovedBlocks."
        default: true
 
    belovedblocks.use.tools.wrench:
        description: "Allows the player to use the wrench of BelovedBlocks."
        default: true
 
    belovedblocks.use.tools.stonecutter:
        description: "Allows the player to use the stonecutter of BelovedBlocks."
        default: true
 
    belovedblocks.craft.blocks.end-portal:
        description: "Allows the player to craft the end portal of BelovedBlocks."
        default: true

    belovedblocks.craft.blocks.portal-nether:
        description: "Allows the player to craft the nether portal of BelovedBlocks."
        default: true
        
    belovedblocks.craft.blocks.end-gateway:
        description: "Allows the player to craft the end gateway of BelovedBlocks."
        default: true
         
    belovedblocks.craft.blocks.burning_furnace:
        description: "Allows the player to craft the burning_furnace of BelovedBlocks."
        default: true
 
    belovedblocks.craft.blocks.burning_smoker:
        description: "Allows the player to craft the burning_smoker of BelovedBlocks."
        default: true
 
    belovedblocks.craft.blocks.burning_bast_furnace:
        description: "Allows the player to craft the burning_bast_furnace of BelovedBlocks."
        default: true
 
    belovedblocks.craft.tools.wrench:
        description: "Allows the player to craft the wrench of BelovedBlocks."
        default: true
 
    belovedblocks.craft.tools.stonecutter:
        description: "Allows the player to craft the stonecutter of BelovedBlocks."
        default: true 