name: BelovedBlocks
description: The return of these beautiful smooth double slabs
main: eu.carrade.amaury.BelovedBlocks.BelovedBlocks
version: 1.0
authors: ["Amaury Carrade", "Florian Cassayre"]

awareness:
  - !@UTF8

commands:
    belovedblocks:
        description: Get the blocks and tools added by BelovedBlocks
        aliases: [bb]
        usage: "See /<command>."

permissions:
    belovedblocks.*:
        description: "Gives access to all BelovedBlocks commands"
        children:
         - belovedblocks.give
    
    belovedblocks.give.*:
        description: "Allows someone to give all tools and blocks of BelovedBlocks"
        children:
         - belovedblocks.give.tool
         - belovedblocks.give.blocks
    
    belovedblocks.give.blocks.*:
        description: "Allows someone to give all blocks of BelovedBlocks"
        children:
         - belovedblocks.give.blocks.stone
         - belovedblocks.give.blocks.sandstone
         - belovedblocks.give.blocks.red-sandstone
         - belovedblocks.give.blocks.quartz
         - belovedblocks.give.blocks.oak
         - belovedblocks.give.blocks.spruce
         - belovedblocks.give.blocks.birch
         - belovedblocks.give.blocks.jungle
         - belovedblocks.give.blocks.acacia
         - belovedblocks.give.blocks.dark-oak
    
    belovedblocks.give.tool.*:
        description: "Allow someone to give the stonecutter of BelovedBlocks."
        children:
         - belovedblocks.give.tool.stonecutter
         - belovedblocks.give.tool.saw
    
    belovedblocks.give.blocks.stone.*:
        description: "Allow someone to give the smooth stone block of BelovedBlocks."
        children:
         - belovedblocks.give.blocks.stone.self
         - belovedblocks.give.blocks.stone.other
    
    belovedblocks.give.blocks.sandstone.*:
        description: "Allow someone to give the smooth sandstone block of BelovedBlocks."
        children:
         - belovedblocks.give.blocks.sandstone.self
         - belovedblocks.give.blocks.sandstone.other
    
    belovedblocks.give.blocks.red-sandstone.*:
        description: "Allow someone to give the smooth red sandstone block of BelovedBlocks."
        children:
         - belovedblocks.give.blocks.red-sandstone.self
         - belovedblocks.give.blocks.red-sandstone.other
    
    belovedblocks.give.blocks.quartz.*:
        description: "Allow someone to give the smooth quartz block of BelovedBlocks."
        children:
         - belovedblocks.give.blocks.quartz.self
         - belovedblocks.give.blocks.quartz.other
    
    belovedblocks.give.blocks.oak.*:
        description: "Allow someone to give the smooth oak block of BelovedBlocks."
        children:
         - belovedblocks.give.blocks.oak.self
         - belovedblocks.give.blocks.oak.other
    
    belovedblocks.give.blocks.spruce.*:
        description: "Allow someone to give the smooth spruce block of BelovedBlocks."
        children:
         - belovedblocks.give.blocks.spruce.self
         - belovedblocks.give.blocks.spruce.other
    
    belovedblocks.give.blocks.birch.*:
        description: "Allow someone to give the smooth birch block of BelovedBlocks."
        children:
         - belovedblocks.give.blocks.birch.self
         - belovedblocks.give.blocks.birch.other
    
    belovedblocks.give.blocks.jungle.*:
        description: "Allow someone to give the smooth jungle block of BelovedBlocks."
        children:
         - belovedblocks.give.blocks.jungle.self
         - belovedblocks.give.blocks.jungle.other
    
    belovedblocks.give.blocks.acacia.*:
        description: "Allow someone to give the smooth acacia block of BelovedBlocks."
        children:
         - belovedblocks.give.blocks.acacia.self
         - belovedblocks.give.blocks.acacia.other
    
    belovedblocks.give.blocks.dark-oak.*:
        description: "Allow someone to give the smooth dark oak block of BelovedBlocks."
        children:
         - belovedblocks.give.blocks.dark-oak.self
         - belovedblocks.give.blocks.dark-oak.other
   
    belovedblocks.give.tool.stonecutter.*:
        description: "Allow someone to give the stonecutter of BelovedBlocks."
        children:
         - belovedblocks.give.tool.stonecutter.self
         - belovedblocks.give.tool.stonecutter.other
   
    belovedblocks.give.tool.saw.*:
        description: "Allow someone to give the saw of BelovedBlocks."
        children:
         - belovedblocks.give.tool.saw.self
         - belovedblocks.give.tool.saw.other
