name: BelovedBlocks
description: The return of these beautiful smooth double slabs
main: eu.carrade.amaury.BelovedBlocks.BelovedBlocks
version: 0.1
authors: ["Amaury Carrade", "Florian Cassayre"]

awareness:
  - !@UTF8


commands:
    belovedblocks:
        description: Get the blocks and tools added by BelovedBlocks
        aliases: [bb]
        usage: "Usage: see /<command>."

permissions:
    
